<template>
  <div class="readme-container">
    <span class="readme-title">
      {{ readmeTitle[titleCount] }}
    </span>
    <div class="readme-img">
      <img :src="readmeImg[count]" alt="">
    </div>
    <span class="readme-message">
      {{ readmeMes[count] }}
    </span>
    <div class="readme-left"
      @click="turnLeft"
    >
      <img src="../../../assets/icons/arrow_left_large.png" alt="">
    </div>
    <div class="readme-right"
      @click="turnRight"
    >
      <img src="../../../assets/icons/arrow_right_large.png" alt="">
    </div>
    <div class="readme-close"
      @click="closeLayer"
    ><img src="../../../assets/icons/close-white.png" alt=""></div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      count: 0,
      titleCount: 0,
      readmeImg: [

      ],
      readmeMes: [
        'The web online system is developed for demonstration purpose. You can select data you want to visualize it on the map. In this application, we designed a map, a leader board, and a toolbar as follow:',
        'This function can add a layer of polygons indicating the district generated by Constrained K-means algorithm. The color of a polygon reveals the AttractRank value of it. \nStep 1: Chose the period you want to visualize. ',
        'Step 2: Explore the map as you wish.',
        'Step 3: You can also interactively explore data by clicking the specified polygon. \nThe figure above shows how the AttractRank values of everyday change over the hour in a day. You can know the date of one line by clicking one point of it.',
        'This function can add a layer of flying routes. Those routes show the connection between districts. It helps us visualize the structure of the network. \nStep 1: Choose the period you want to visualize. In this function, you can chose more than one hour.',
        'Step 2: Explore the map as you wish. The figure below shows records of all days.',
        'This function can show a contrasting view for the convenience of comparing AttractRank value of different periods. \nStep 1: Open the contrast view.\nStep 2: Click “View AttractRank value” and select two periods.',
        'Step 3: Now you can compare AttractRank value of different periods.',
        'This function allows you to clean layers added by the other functions.'
      ],
      readmeTitle: [
        'README',
        'Illustrate the AttractRank values',
        'Add flying route layer',
        'Open/ Close a contrast view',
        'Clean Layers'
      ]
    }
  },
  methods: {
    closeLayer() {
      this.$store.state.showReadme = false;
    },
    turnLeft() {
      if (this.$data.count <= 0) {
        return ;
      }
      this.$data.count--;
    },
    turnRight() {
      if (this.$data.count >= 8) {
        return ;
      }
      this.$data.count++;
    }
  },
  watch: {
    count(newVal) {
      if (newVal == 0) {
        this.$data.titleCount = 0;
      } else if (newVal <= 3) {
        this.$data.titleCount = 1;
      } else if (newVal <= 5) {
        this.$data.titleCount = 2;
      } else if (newVal <= 7) {
        this.$data.titleCount = 3;
      } else {
        this.$data.titleCount = 4;
      }
    }
  }
}
</script>

<style lang="scss" scoped>
%flex-center {
  display: flex;
  justify-content: center;
  align-items: center;
}

.readme-container {
  position: absolute;
  z-index: 112;
  width: 100vw;
  height: 100vh;
  background-color: rgba($color: #000000, $alpha: 0.4);
  left: 0;
  top: 0;

  .readme-img {
    width: 80%;
    height: 80vh;
    margin: 0.2rem auto;
    margin-bottom: 0;

    img {
      width: 100%;
      height: 100%;
    }
  }

  .readme-title {
    display: block;
    color: #fff;
    font-size: 26px;
    margin: 0.2rem auto;
  }

  .readme-message {
    display: block;
    color: #fff;
    font-size: 20px;
    width: 80%;
    margin: 0.2rem auto;
    text-align: start;
  }

  .readme-left {
    @extend %flex-center;

    cursor: pointer;
    position: absolute;
    left: 0;
    top: 0;
    width: 1rem;
    height: 100vh;

    img {
      width: 30px;
      height: 49px;
    }
  }
  .readme-right {
    @extend %flex-center;

    cursor: pointer;
    position: absolute;
    right: 0;
    top: 0;
    width: 1rem;
    height: 100vh;

    img {
      width: 30px;
      height: 49px;
    }
  }

  .readme-left:hover,
  .readme-right:hover {
    background-color: rgba($color: #fff, $alpha: .3);
  }

  .readme-close {
    cursor: pointer;
    position: absolute;
    right: 1.3rem;
    top: 0.1rem;
    width: 50px;
    height: 50px;

    img {
      width: 50px;
      height: 50px;
    }
  }
}
</style>
